version: '3'

services:
  db:
    container_name: 'db'
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    volumes:
    - ./mysql-data:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
    - MYSQL_ROOT_HOST=${DOCKER_MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${DB_NAME}
    - MYSQL_USER=${DB_USER}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    - TZ="Asia/Tokyo"
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./redis-data:/data
  app:
    build: .
    command: python -u manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
