version: '3'

services:
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./redis-data:/data
  app:
    build: .
    command: python -u manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - redis
